import {
  FlyingGoomba,
  GreenParatroopa,
  RedParatroopa,
  RedSuperKoopa,
  YellowSuperKoopa,
} from '@classes/entities/enemies';
import { Coin, Mushroom, Star } from '@classes/entities/interactables';
import {
  AnchoredPosition,
  FreePosition,
  LevelScene,
  SpawnEvent,
} from '@classes/scenes';

export default new LevelScene({
  name: 'overworld',
  title: 'The Overworld',
  song: 'overworld',
  spawnData: [
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.5), 1),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.1), 2),
    new SpawnEvent(Coin, new AnchoredPosition('x', 0.7), 0.5),
    new SpawnEvent(Coin, new AnchoredPosition('x', 0.7), 0.5),
    new SpawnEvent(Coin, new AnchoredPosition('x', 0.7), 0.5),
    new SpawnEvent(YellowSuperKoopa, new AnchoredPosition('x', 0.5), 1),
    new SpawnEvent(YellowSuperKoopa, new AnchoredPosition('x', 0.7), 1.5),
    new SpawnEvent(GreenParatroopa, new AnchoredPosition('x', 0.3), 1),
    new SpawnEvent(RedParatroopa, new AnchoredPosition('x', 0), 2),
    new SpawnEvent(RedSuperKoopa, new AnchoredPosition('x', 0.3), 2),
    new SpawnEvent(RedSuperKoopa, new AnchoredPosition('x', 0.8), 1),
    new SpawnEvent(RedSuperKoopa, new AnchoredPosition('x', 0.5), 1),
    new SpawnEvent(RedSuperKoopa, new AnchoredPosition('x', 0.3), 1),
    new SpawnEvent(Coin, new AnchoredPosition('x', 0.1), 1),
    new SpawnEvent(Coin, new AnchoredPosition('x', 0.1), 0.5),
    new SpawnEvent(Coin, new AnchoredPosition('x', 0.1), 0.5),
    new SpawnEvent(Coin, new AnchoredPosition('x', 0.1), 0.5),
    new SpawnEvent(YellowSuperKoopa, new AnchoredPosition('x', 0.3), 0),
    new SpawnEvent(YellowSuperKoopa, new AnchoredPosition('x', 0.5), 0),
    new SpawnEvent(YellowSuperKoopa, new AnchoredPosition('x', 0.7), 0),
    new SpawnEvent(YellowSuperKoopa, new AnchoredPosition('x', 0.9), 0),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.15), 1),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.75), 1),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.15), 0.5),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.75), 0.5),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.15), 0.5),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.75), 0.5),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.15), 0.5),
    new SpawnEvent(FlyingGoomba, new AnchoredPosition('x', 0.75), 0.5),
    new SpawnEvent(Mushroom, new AnchoredPosition('x', 0.15), 1.5),
    new SpawnEvent(GreenParatroopa, new AnchoredPosition('x', 0.3), 2),
    new SpawnEvent(RedParatroopa, new AnchoredPosition('x', 0.3), 1.5),
    new SpawnEvent(GreenParatroopa, new AnchoredPosition('x', 0.3), 0.5),
    new SpawnEvent(RedParatroopa, new AnchoredPosition('x', 0.3), 0.5),
    new SpawnEvent(Star, new FreePosition(0.8, 0.5), 3),
  ],
});
