import {
  FlyingGoomba,
  GreenParatroopa,
  RedParatroopa,
  RedSuperKoopa,
  YellowSuperKoopa,
} from '@classes/entities/enemies';
import { Coin, Mushroom, Star } from '@classes/entities/interactables';
import {
  AnchoredPosition,
  FreePosition,
  Instruction,
  LevelScene,
} from '@classes/scenes';

export default new LevelScene({
  name: 'overworld',
  title: 'The Overworld',
  song: 'overworld',
  spawnData: [
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.5), 1),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.1), 3),
    new Instruction(Coin, new AnchoredPosition('x', 0.7), 3.5),
    new Instruction(Coin, new AnchoredPosition('x', 0.7), 4),
    new Instruction(Coin, new AnchoredPosition('x', 0.7), 4.5),
    new Instruction(YellowSuperKoopa, new AnchoredPosition('x', 0.5), 5.5),
    new Instruction(YellowSuperKoopa, new AnchoredPosition('x', 0.7), 7),
    new Instruction(GreenParatroopa, new AnchoredPosition('x', 0.3), 8),
    new Instruction(RedParatroopa, new AnchoredPosition('x', 0), 10),
    new Instruction(RedSuperKoopa, new AnchoredPosition('x', 0.3), 12),
    new Instruction(RedSuperKoopa, new AnchoredPosition('x', 0.8), 13),
    new Instruction(RedSuperKoopa, new AnchoredPosition('x', 0.5), 14),
    new Instruction(RedSuperKoopa, new AnchoredPosition('x', 0.3), 15),
    new Instruction(Coin, new AnchoredPosition('x', 0.1), 16),
    new Instruction(Coin, new AnchoredPosition('x', 0.1), 16.5),
    new Instruction(Coin, new AnchoredPosition('x', 0.1), 17),
    new Instruction(Coin, new AnchoredPosition('x', 0.1), 17.5),
    new Instruction(YellowSuperKoopa, new AnchoredPosition('x', 0.3), 17),
    new Instruction(YellowSuperKoopa, new AnchoredPosition('x', 0.5), 17),
    new Instruction(YellowSuperKoopa, new AnchoredPosition('x', 0.7), 17),
    new Instruction(YellowSuperKoopa, new AnchoredPosition('x', 0.9), 17),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.15), 19),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.15), 20),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.15), 21),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.15), 22),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.15), 23),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.75), 21),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.75), 22),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.75), 23),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.75), 24),
    new Instruction(FlyingGoomba, new AnchoredPosition('x', 0.75), 25),
    new Instruction(Mushroom, new AnchoredPosition('x', 0.15), 26),
    new Instruction(GreenParatroopa, new AnchoredPosition('x', 0.3), 28),
    new Instruction(RedParatroopa, new AnchoredPosition('x', 0.3), 28.5),
    new Instruction(GreenParatroopa, new AnchoredPosition('x', 0.3), 29),
    new Instruction(RedParatroopa, new AnchoredPosition('x', 0.3), 29.5),
    new Instruction(Star, new FreePosition(0.8, 0.5), 33),
  ],
});
